# Generated by Django 5.1.2 on 2025-01-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allChemicalsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemName', models.CharField(max_length=255)),
                ('chemLocation', models.CharField(max_length=255)),
                ('chemStorageType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='currentlyInStorageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemBottleIDNUM', models.IntegerField()),
                ('chemName', models.CharField(max_length=255)),
                ('chemLocation', models.CharField(max_length=255, null=True)),
                ('chemLocationCabinet', models.CharField(max_length=255, null=True)),
                ('chemLocationShelf', models.CharField(max_length=255, null=True)),
                ('chemAmountInBottle', models.FloatField()),
                ('chemAmountUnit', models.CharField(max_length=255, null=True)),
                ('chemConcentration', models.CharField(max_length=255, null=True)),
                ('chemSDS', models.IntegerField(null=True)),
                ('chemStorageType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QRCodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
