# Generated by Django 5.1.1 on 2025-01-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlyinstoragetable',
            name='chemCheckedOut',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
