# Generated by Django 5.1.5 on 2025-02-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlyinstoragetable',
            name='chemTest',
        ),
        migrations.AlterField(
            model_name='currentlyinstoragetable',
            name='chemSDS',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
