# Generated by Django 5.1.2 on 2024-11-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlyinstoragetable',
            name='chemConcentration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='currentlyinstoragetable',
            name='chemSDS',
            field=models.IntegerField(null=True),
        ),
    ]
