# Generated by Django 5.1.1 on 2025-01-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_currentlyinstoragetable_chemcheckedout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlyinstoragetable',
            name='chemCheckedOut',
            field=models.BooleanField(default=False),
        ),
    ]
