# Generated by Django 5.1.2 on 2024-11-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_currentlyinstoragetable_chemconcentration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlyinstoragetable',
            name='chemLocation',
        ),
        migrations.AddField(
            model_name='currentlyinstoragetable',
            name='chemAmountUnit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='currentlyinstoragetable',
            name='chemLocationCabinet',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='currentlyinstoragetable',
            name='chemLocationShelf',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
