# Generated by Django 4.2.16 on 2024-10-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0002_director_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="director",
        ),
        migrations.DeleteModel(
            name="Director",
        ),
        migrations.DeleteModel(
            name="Movie",
        ),
    ]
