# Generated by Django 5.1.1 on 2025-02-04 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_currentlyinstoragetable_chemcheckedout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlyinstoragetable',
            name='chemCheckedOutBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currentlyinstoragetable',
            name='chemCheckedOutDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
