# Generated by Django 5.1.2 on 2024-11-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_currentlyinstoragetable_chemlocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlyinstoragetable',
            name='chemConcentration',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
