# Generated by Django 5.1.1 on 2025-02-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_currentlyinstoragetable_chemcheckedoutby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlyinstoragetable',
            name='chemTest',
        ),
        migrations.AlterField(
            model_name='currentlyinstoragetable',
            name='chemSDS',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
