services:
  web:
    build: ./chemistry
    container_name: django_web
    ports:
      - "8000:8000"
    restart: always
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    depends_on:
      - mysql
    volumes:
      - ./chemistry:/app  # Mount the project directory
      - static_volume:/app/static_collected
    command: >
      sh -c "until nc -z mysql 3306; do echo 'Waiting for MySQL...'; sleep 2; done && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  static_volume:
  mysql_data: