# Generated by Django 5.1.5 on 2025-04-15 19:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='allChemicals',
            fields=[
                ('chemID', models.AutoField(primary_key=True, serialize=False)),
                ('chemMaterial', models.CharField(max_length=255)),
                ('chemName', models.CharField(max_length=255)),
                ('chemLocationRoom', models.CharField(default='None', max_length=255)),
                ('chemLocationCabinet', models.CharField(default='None', max_length=255)),
                ('chemLocationShelf', models.CharField(default='None', max_length=255)),
                ('chemAmountTotal', models.FloatField(blank=True, default=0, max_length=255, null=True)),
                ('chemAmountExpected', models.FloatField(blank=True, default=0, max_length=255, null=True)),
                ('chemAmountPercentage', models.FloatField(blank=True, default=0, max_length=255, null=True)),
                ('chemAmountUnit', models.CharField(blank=True, max_length=255, null=True)),
                ('chemConcentration', models.CharField(blank=True, max_length=255, null=True)),
                ('chemSDS', models.CharField(blank=True, max_length=20, null=True)),
                ('chemNotes', models.CharField(blank=True, max_length=255, null=True)),
                ('chemInstrument', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'allchemicalstable',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='QRCodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='individualChemicals',
            fields=[
                ('chemBottleIDNUM', models.IntegerField(primary_key=True, serialize=False)),
                ('chemMaterial', models.CharField(blank=True, max_length=255, null=True)),
                ('chemLocationRoom', models.CharField(default='None', max_length=255)),
                ('chemLocationCabinet', models.CharField(default='None', max_length=255)),
                ('chemLocationShelf', models.CharField(default='None', max_length=255)),
                ('chemAmountInBottle', models.CharField(default='0', max_length=255)),
                ('chemCheckedOut', models.BooleanField(default=False)),
                ('chemCheckedOutDate', models.DateTimeField(blank=True, null=True)),
                ('chemAssociated', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='chemistry_system.allchemicals')),
                ('chemCheckedOutBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'currentlyinstoragetable',
            },
        ),
    ]
