# Generated by Django 5.1.5 on 2025-04-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allchemicals',
            options={'permissions': [('can_access_restricted', 'Can access restricted pages')]},
        ),
    ]
