# Generated by Django 5.1.5 on 2025-02-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlyinstoragetable',
            name='chemStorageType',
        ),
        migrations.AlterField(
            model_name='allchemicalstable',
            name='material_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
