# Generated by Django 5.1.5 on 2025-02-18 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chemistry_system",
            "0002_remove_currentlyinstoragetable_chemstoragetype_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=255)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
