# Generated by Django 5.1.5 on 2025-02-19 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0003_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='allChemicalsTable',
        ),
    ]
