# Generated by Django 5.1.5 on 2025-02-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0004_delete_allchemicalstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='allChemicalsTable',
            fields=[
                ('chemID', models.IntegerField(primary_key=True, serialize=False)),
                ('chemMaterial', models.CharField(max_length=255)),
                ('chemName', models.CharField(max_length=255)),
                ('chemLocationRoom', models.CharField(default='None', max_length=255)),
                ('chemLocationCabinet', models.CharField(default='None', max_length=255)),
                ('chemLocationShelf', models.CharField(default='None', max_length=255)),
                ('chemAmountInBottle', models.CharField(default='0', max_length=255)),
                ('chemAmountUnit', models.CharField(max_length=255, null=True)),
                ('chemConcentration', models.CharField(max_length=255, null=True)),
                ('chemSDS', models.CharField(max_length=20, null=True)),
                ('chemNotes', models.CharField(max_length=255, null=True)),
                ('chemInstrument', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
