# Generated by Django 5.1.5 on 2025-02-19 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0005_allchemicalstable'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlyinstoragetable',
            name='chemAssociated',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chemistry_system.allchemicalstable'),
        ),
    ]
