# Generated by Django 5.1.5 on 2025-02-19 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0006_currentlyinstoragetable_chemassociated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlyinstoragetable',
            name='chemAmountUnit',
        ),
        migrations.RemoveField(
            model_name='currentlyinstoragetable',
            name='chemConcentration',
        ),
        migrations.RemoveField(
            model_name='currentlyinstoragetable',
            name='chemInstrument',
        ),
        migrations.RemoveField(
            model_name='currentlyinstoragetable',
            name='chemMaterial',
        ),
        migrations.RemoveField(
            model_name='currentlyinstoragetable',
            name='chemName',
        ),
        migrations.RemoveField(
            model_name='currentlyinstoragetable',
            name='chemNotes',
        ),
        migrations.RemoveField(
            model_name='currentlyinstoragetable',
            name='chemSDS',
        ),
    ]
