# Generated by Django 5.1.5 on 2025-02-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0007_remove_currentlyinstoragetable_chemamountunit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allchemicalstable',
            old_name='chemAmountInBottle',
            new_name='chemAmountTotal',
        ),
    ]
