# Generated by Django 5.1.5 on 2025-02-27 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0007_remove_currentlyinstoragetable_chemamountunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlyinstoragetable',
            name='chemAssociated',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='chemistry_system.allchemicalstable'),
        ),
    ]
