# Generated by Django 5.1.5 on 2025-02-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0008_alter_currentlyinstoragetable_chemassociated'),
        ('chemistry_system', '0008_rename_chemamountinbottle_allchemicalstable_chemamounttotal'),
    ]

    operations = [
    ]
