# Generated by Django 5.1.5 on 2025-03-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0008_rename_chemamountinbottle_allchemicalstable_chemamounttotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='allchemicalstable',
            name='chemManufacturerBarcode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
