# Generated by Django 5.1.5 on 2025-03-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0009_allchemicalstable_chemmanufacturerbarcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allchemicals',
            name='chemManufacturerBarcode',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
