# Generated by Django 5.1.5 on 2025-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0009_merge_20250227_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='allchemicalstable',
            name='chemAmountExpected',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='allchemicalstable',
            name='chemAmountPercentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='allchemicalstable',
            name='chemAmountTotal',
            field=models.FloatField(default=0),
        ),
    ]
