# Generated by Django 5.1.5 on 2025-03-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0010_allchemicalstable_chemamountexpected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualchemicals',
            name='chemAmountUnit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individualchemicals',
            name='chemConcentration',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individualchemicals',
            name='chemInstrument',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individualchemicals',
            name='chemNotes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individualchemicals',
            name='chemSDS',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
