# Generated by Django 5.1.5 on 2025-03-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0010_allchemicalstable_chemamountexpected_and_more'),
        ('chemistry_system', '0010_alter_allchemicalstable_chemmanufacturerbarcode'),
    ]

    operations = [
    ]
