# Generated by Django 5.1.5 on 2025-03-25 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0010_allchemicalstable_chemamountexpected_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='allChemicalsTable',
            new_name='allChemicals',
        ),
        migrations.RenameModel(
            old_name='currentlyInStorageTable',
            new_name='individualChemicals',
        ),
        migrations.AlterModelTable(
            name='allchemicals',
            table='allchemicalstable',
        ),
        migrations.AlterModelTable(
            name='individualchemicals',
            table='currentlyinstoragetable',
        ),
    ]
