# Generated by Django 5.1.5 on 2025-03-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0011_rename_allchemicalstable_allchemicals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualchemicals',
            name='chemMaterial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
