# Generated by Django 5.1.5 on 2025-03-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0011_merge_20250306_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='media/barcodes/')),
            ],
        ),
    ]
