# Generated by Django 5.1.5 on 2025-03-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0012_barcode'),
        ('chemistry_system', '0012_individualchemicals_chemmaterial'),
    ]

    operations = [
    ]
