# Generated by Django 5.1.5 on 2025-04-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0012_individualchemicals_chemmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allchemicals',
            name='chemID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
