# Generated by Django 5.1.5 on 2025-04-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0012_individualchemicals_chemmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allchemicals',
            name='chemAmountExpected',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allchemicals',
            name='chemAmountPercentage',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allchemicals',
            name='chemAmountTotal',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allchemicals',
            name='chemAmountUnit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allchemicals',
            name='chemConcentration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allchemicals',
            name='chemNotes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allchemicals',
            name='chemSDS',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
