# Generated by Django 5.1.5 on 2025-04-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0011_currentlyinstoragetable_chemamountunit_and_more'),
        ('chemistry_system', '0011_rename_allchemicalstable_allchemicals_and_more'),
    ]

    operations = [
    ]
