# Generated by Django 5.1.5 on 2025-04-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0012_individualchemicals_chemmaterial'),
        ('chemistry_system', '0013_merge_20250401_1733'),
    ]

    operations = [
    ]
