# Generated by Django 5.1.5 on 2025-04-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry_system', '0014_merge_20250401_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualchemicals',
            name='chemMaterial',
        ),
        migrations.AlterModelTable(
            name='allchemicals',
            table=None,
        ),
        migrations.AlterModelTable(
            name='individualchemicals',
            table=None,
        ),
    ]
